# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
      - init

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: |
          npm ci
          TARGET_VERSION=$(jq -r '.version' package.json)
          PACKAGE_NAME=$(jq -r '.name' package.json)
          echo "CURRENT_VERSION=$(npm view $PACKAGE_NAME version)" >> $GITHUB_ENV
          if [ "$TARGET_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Publishing version $TARGET_VERSION to npm"
            npm publish --access public
          else
            echo "Version $TARGET_VERSION already published, skipping publish"
            exit 0
          fi
